// Bundles server/*.ts into api/*.js for Vercel. The shared pipeline code uses explicit .ts imports
// (needed by Node's type stripping for local scripts), which Vercel's per-file TypeScript compile
// doesn't rewrite — so the function ships as one pre-bundled file. npm packages stay external;
// Vercel installs them and traces what the bundle needs.
import { defineConfig } from 'rolldown'
import pkg from './package.json' with { type: 'json' }

const external = Object.keys(pkg.dependencies ?? {})

export default defineConfig({
    input: { news: 'server/news.ts', 'power-units': 'server/power-units.ts' },
    platform: 'node',
    external: id => external.some(dep => id === dep || id.startsWith(`${dep}/`)),
    output: {
        dir: 'api',
        format: 'esm',
        entryFileNames: '[name].js',
        // Code shared between functions. Vercel turns every file in api/ into an endpoint except
        // underscore-prefixed paths, so shared chunks live in api/_chunks/.
        chunkFileNames: '_chunks/[name].js', // Stable names: rebuilds overwrite instead of piling up
        banner: '// GENERATED by `npm run build:api` from server/*.ts — do not edit.',
    },
})
