// GENERATED by `npm run build:api` from server/*.ts — do not edit.
//#region scripts/news/robots.ts
const rules = /* @__PURE__ */ new Map();
async function disallowed(origin, fetchText) {
	if (rules.has(origin)) return rules.get(origin);
	let paths = [];
	try {
		const txt = await fetchText(`${origin}/robots.txt`);
		let applies = false;
		for (const raw of txt.split(/\r?\n/)) {
			const [key, ...rest] = raw.split("#")[0].trim().split(":");
			const value = rest.join(":").trim();
			if (/^user-agent$/i.test(key)) applies = value === "*";
			else if (applies && /^disallow$/i.test(key) && value) paths.push(value);
		}
	} catch {
		paths = [];
	}
	rules.set(origin, paths);
	return paths;
}
async function allowedByRobots(url, fetchText) {
	const { origin, pathname } = new URL(url);
	return !(await disallowed(origin, fetchText)).some((prefix) => pathname.startsWith(prefix));
}
//#endregion
export { allowedByRobots as t };
