// GENERATED by `npm run build:api` from server/*.ts — do not edit.
//#region scripts/lib/http.ts
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function queue(gapMs) {
	let nextSlot = 0;
	return async () => {
		const now = Date.now();
		const start = Math.max(now, nextSlot);
		nextSlot = start + gapMs;
		await wait(start - now);
	};
}
const apiSlot = queue(400);
const pageSlot = queue(1e3);
const MAX_RETRIES = 8;
const MAX_BACKOFF_MS = 6e4;
async function fetchJson(url, emptyOn404) {
	for (let attempt = 0;; attempt++) {
		await apiSlot();
		const res = await fetch(url);
		if ((res.status === 429 || res.status >= 500) && attempt < MAX_RETRIES) {
			const retryAfter = Number(res.headers.get("retry-after")) * 1e3;
			const backoff = Math.min(MAX_BACKOFF_MS, retryAfter || 2e3 * 2 ** attempt);
			console.warn(`  ${res.status} — waiting ${Math.round(backoff / 1e3)}s`);
			await wait(backoff);
			continue;
		}
		if (res.status === 404 && emptyOn404) return [];
		if (!res.ok) throw new Error(`${res.status} ${url}`);
		return res.json();
	}
}
const USER_AGENT = "f1-dashboard-news/1.0 (personal project; summaries with source links)";
async function politeGet(url) {
	for (let attempt = 0;; attempt++) {
		await pageSlot();
		const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
		if (res.status >= 500 && attempt < 3) {
			await wait(3e3 * (attempt + 1));
			continue;
		}
		if (!res.ok) throw new Error(`${res.status} ${url}`);
		return res;
	}
}
async function fetchPage(url) {
	return (await politeGet(url)).text();
}
const openF1Url = (path) => `https://api.openf1.org/v1${path}`;
async function fetchBytes(url) {
	return new Uint8Array(await (await politeGet(url)).arrayBuffer());
}
//#endregion
//#region scripts/news/robots.ts
const rules = /* @__PURE__ */ new Map();
async function disallowed(origin, fetchText) {
	if (rules.has(origin)) return rules.get(origin);
	let paths = [];
	try {
		const txt = await fetchText(`${origin}/robots.txt`);
		let applies = false;
		for (const raw of txt.split(/\r?\n/)) {
			const [key, ...rest] = raw.split("#")[0].trim().split(":");
			const value = rest.join(":").trim();
			if (/^user-agent$/i.test(key)) applies = value === "*";
			else if (applies && /^disallow$/i.test(key) && value) paths.push(value);
		}
	} catch {
		paths = [];
	}
	rules.set(origin, paths);
	return paths;
}
async function allowedByRobots(url, fetchText) {
	const { origin, pathname } = new URL(url);
	return !(await disallowed(origin, fetchText)).some((prefix) => pathname.startsWith(prefix));
}
//#endregion
export { openF1Url as a, fetchPage as i, fetchBytes as n, fetchJson as r, allowedByRobots as t };
