// GENERATED by `npm run build:api` from server/*.ts — do not edit.
import Anthropic from "@anthropic-ai/sdk";
import { get, put } from "@vercel/blob";
import { waitUntil } from "@vercel/functions";
//#region src/data/raceNews.json
var raceNews_default = { "2026": { "14": {
	"headline": "Kimi Antonelli turned a well-timed VSC into a fourth-straight-style stroll at F1's processional Madring debut, leaving pole-sitter Lando Norris third and the title all but decided.",
	"bullets": [
		{
			"text": "**Antonelli** never had to make a pass to win: the virtual safety car for Lance Stroll's lap-12 retirement fell at the perfect moment for him and a moment too late for Norris, whose stop a lap later was also slow. He called it his least remarkable victory of the year and said he felt for Norris, who he thought deserved it.",
			"sources": [6]
		},
		{
			"text": "**Norris** produced what he rated the best qualifying lap of his career — Andrea Stella called the bulk of it \"a masterpiece\" despite a scruffy final corner — to beat Antonelli to pole by 0.011s, then lost the race purely to VSC timing before clipping the Turn 7 wall.",
			"sources": [2, 6]
		},
		{
			"text": "**McLaren**'s weekend was doubly poor: Piastri was off the pace all through qualifying, picked up front wing damage in a lap-one clash with Russell, and was then left stuck in a midfield train behind Bortoleto and Colapinto after the team pitted him knowing that was a risk.",
			"sources": [2, 6]
		},
		{
			"text": "**Hamilton** was ahead of Verstappen off the line and looked a podium contender before a long brake pedal and a brake malfunction ended his race on lap six — after which he publicly conceded the title, saying Antonelli and Mercedes deserved it, with Ferrari's cushion over McLaren for second in the constructors' now 52 points.",
			"sources": [4, 6]
		},
		{
			"text": "**The Madring** drew praise as a qualifying challenge but delivered almost no on-track passing — Lawson on Colapinto and Russell on Lawson were the notable exceptions — and circuit chiefs have already confirmed revisions to the Turn 5/6 chicane, Turn 13 and Turn 20 for 2027; those changes had been proposed before this year's race but were shelved to avoid homologation and construction delays.",
			"sources": [4, 5]
		},
		{
			"text": "**Pirelli** defended the C2/C3/C4 allocation after Friday's heavy degradation evaporated into a routine one-stopper — Gasly ran his starting set to the penultimate lap before his mandatory change — arguing softer rubber would only have produced a tyre-management race given the roughly 25-second pitlane loss, one of the longest of the season.",
			"sources": [3]
		},
		{
			"text": "**Colapinto** led the midfield home in seventh, holding off a quicker Piastri, and credited his qualifying execution to what he learned from Gasly's Monza pole lap; Alpine's deficit to Racing Bulls in the fight for fifth is down to nine points.",
			"sources": [4, 6]
		},
		{
			"text": "Away from the track, FIA president Mohammed Ben Sulayem has been discussing extra assistance for **Honda** with Fernando Alonso and Lawrence Stroll, with Mercedes and Red Bull said to be receptive, while Laurent Mekies admitted Red Bull's unexplained in-race car performance degradation is still unsolved and likely to run into next season.",
			"sources": [4]
		}
	],
	"quotes": [
		{
			"speaker": "Lewis Hamilton",
			"quote": "There's no stopping him and Mercedes this year",
			"source": 4
		},
		{
			"speaker": "Oscar Piastri",
			"quote": "The medium tyre was just awful. It was good for literally one lap, but then it was terrible.",
			"source": 3
		},
		{
			"speaker": "Charles Leclerc",
			"quote": "But in the race, there are some corners and it doesn't require a big change, I think just a small change or two small changes could change significantly the racing that we have.",
			"source": 5
		},
		{
			"speaker": "Fernando Alonso",
			"quote": "The engine was very bad today",
			"source": 6
		}
	],
	"generatedAt": "2026-09-24T15:09:42.601Z",
	"model": "claude-opus-5",
	"sources": [
		{
			"id": 1,
			"site": "The Race",
			"title": "F1's TV visuals are letting its Madrid track down",
			"url": "https://www.the-race.com/formula-1/f1-madrid-spanish-gp-tv-coverage-madring/",
			"published": "2026-09-12"
		},
		{
			"id": 2,
			"site": "The Race",
			"title": "Winners and losers from Spanish GP F1 qualifying at the Madring",
			"url": "https://www.the-race.com/formula-1/f1-2026-spanish-grand-prix-qualifying-winners-losers/",
			"published": "2026-09-12"
		},
		{
			"id": 3,
			"site": "The Race",
			"title": "This 'fix' wouldn't have saved F1's Spanish GP",
			"url": "https://www.the-race.com/formula-1/suggested-fix-would-not-have-saved-f1-spanish-gp-madring/",
			"published": "2026-09-15"
		},
		{
			"id": 4,
			"site": "The Race",
			"title": "Everything we learned from F1's 2026 Spanish Grand Prix",
			"url": "https://www.the-race.com/formula-1/everything-we-learned-f1-2026-spanish-grand-prix-madring/",
			"published": "2026-09-14"
		},
		{
			"id": 5,
			"site": "The Race",
			"title": "Three changes Madring will make after terrible F1 debut",
			"url": "https://www.the-race.com/formula-1/madring-f1-spanish-gp-circuit-three-changes-planned-2027/",
			"published": "2026-09-14"
		},
		{
			"id": 6,
			"site": "The Race",
			"title": "Winners and losers from F1's 2026 Spanish Grand Prix",
			"url": "https://www.the-race.com/formula-1/winners-losers-from-f1-2026-spanish-grand-prix/",
			"published": "2026-09-13"
		},
		{
			"id": 7,
			"site": "The Race",
			"title": "Winners and losers from F1 Madring practice",
			"url": "https://www.the-race.com/formula-1/winners-and-losers-from-f1-madring-friday-practice/",
			"published": "2026-09-11"
		}
	],
	"links": []
} } };
//#endregion
//#region src/lib/ergast.ts
const BASE_URL = "https://api.jolpi.ca/ergast/f1";
const PAGE_SIZE = 100;
async function ergastFetch(path) {
	const res = await fetch(`${BASE_URL}${path}`);
	if (!res.ok) throw new Error(`Ergast fetch failed: ${res.status}`);
	return res.json();
}
async function fetchAllRacePages(path) {
	const byRound = /* @__PURE__ */ new Map();
	let offset = 0;
	let total;
	do {
		const data = await ergastFetch(`${path}?limit=${PAGE_SIZE}&offset=${offset}`);
		total = parseInt(data.MRData.total);
		for (const race of data.MRData.RaceTable.Races) {
			const existing = byRound.get(race.round);
			if (!existing) {
				byRound.set(race.round, race);
				continue;
			}
			existing.Results = [...existing.Results ?? [], ...race.Results ?? []];
			existing.SprintResults = [...existing.SprintResults ?? [], ...race.SprintResults ?? []];
			existing.QualifyingResults = [...existing.QualifyingResults ?? [], ...race.QualifyingResults ?? []];
		}
		offset += PAGE_SIZE;
	} while (offset < total);
	return [...byRound.values()];
}
function mapDriver(d) {
	return {
		driverId: d.driverId,
		code: d.code,
		permanentNumber: d.permanentNumber,
		givenName: d.givenName,
		familyName: d.familyName,
		nationality: d.nationality,
		dateOfBirth: d.dateOfBirth
	};
}
function mapConstructor(c) {
	return {
		constructorId: c.constructorId,
		name: c.name,
		nationality: c.nationality
	};
}
function mapResult(r) {
	return {
		position: parseInt(r.position),
		positionText: r.positionText,
		points: parseFloat(r.points),
		grid: parseInt(r.grid),
		laps: parseInt(r.laps),
		status: r.status,
		time: r.Time?.time,
		driver: mapDriver(r.Driver),
		constructor: mapConstructor(r.Constructor),
		fastestLap: r.FastestLap ? {
			rank: parseInt(r.FastestLap.rank),
			lap: parseInt(r.FastestLap.lap),
			time: r.FastestLap.Time?.time
		} : void 0
	};
}
function mapRace(race, results = race.Results ?? []) {
	return {
		season: parseInt(race.season),
		round: parseInt(race.round),
		raceName: race.raceName,
		circuitId: race.Circuit.circuitId,
		circuitName: race.Circuit.circuitName,
		date: race.date,
		results: results.map(mapResult)
	};
}
function standingsPath(season, round, kind) {
	return round ? `/${season}/${round}/${kind}.json` : `/${season}/${kind}.json`;
}
async function fetchDriverStandings(season, round) {
	return ((await ergastFetch(standingsPath(season, round, "driverStandings"))).MRData.StandingsTable.StandingsLists[0]?.DriverStandings ?? []).map((entry) => ({
		position: parseInt(entry.position),
		points: parseFloat(entry.points),
		wins: parseInt(entry.wins),
		driver: mapDriver(entry.Driver),
		constructor: mapConstructor(entry.Constructors[entry.Constructors.length - 1])
	}));
}
async function fetchConstructorStandings(season, round) {
	return ((await ergastFetch(standingsPath(season, round, "constructorStandings"))).MRData.StandingsTable.StandingsLists[0]?.ConstructorStandings ?? []).map((entry) => ({
		position: parseInt(entry.position),
		points: parseFloat(entry.points),
		wins: parseInt(entry.wins),
		constructor: mapConstructor(entry.Constructor)
	}));
}
async function fetchSchedule(season) {
	return (await ergastFetch(`/${season}.json?limit=${PAGE_SIZE}`)).MRData.RaceTable.Races.map((race) => ({
		season: parseInt(race.season),
		round: parseInt(race.round),
		raceName: race.raceName,
		circuitId: race.Circuit.circuitId,
		circuitName: race.Circuit.circuitName,
		locality: race.Circuit.Location.locality,
		country: race.Circuit.Location.country,
		date: race.date,
		firstPracticeDate: race.FirstPractice?.date,
		sprintDate: race.Sprint?.date
	}));
}
async function fetchAllRaces(season) {
	return (await fetchAllRacePages(`/${season}/results.json`)).map((race) => mapRace(race));
}
async function fetchAllSprints(season) {
	return (await fetchAllRacePages(`/${season}/sprint.json`)).map((race) => mapRace(race, race.SprintResults ?? []));
}
async function fetchPoles(season) {
	return (await fetchAllRacePages(`/${season}/qualifying.json`)).flatMap((race) => {
		const pole = race.QualifyingResults?.find((q) => q.position === "1");
		return pole ? [{
			round: parseInt(race.round),
			driver: mapDriver(pole.Driver),
			constructor: mapConstructor(pole.Constructor)
		}] : [];
	});
}
//#endregion
//#region scripts/lib/http.ts
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function queue(gapMs) {
	let nextSlot = 0;
	return async () => {
		const now = Date.now();
		const start = Math.max(now, nextSlot);
		nextSlot = start + gapMs;
		await wait(start - now);
	};
}
const apiSlot = queue(400);
const pageSlot = queue(1e3);
const MAX_RETRIES = 8;
const MAX_BACKOFF_MS = 6e4;
async function fetchJson(url, emptyOn404) {
	for (let attempt = 0;; attempt++) {
		await apiSlot();
		const res = await fetch(url);
		if ((res.status === 429 || res.status >= 500) && attempt < MAX_RETRIES) {
			const retryAfter = Number(res.headers.get("retry-after")) * 1e3;
			const backoff = Math.min(MAX_BACKOFF_MS, retryAfter || 2e3 * 2 ** attempt);
			console.warn(`  ${res.status} — waiting ${Math.round(backoff / 1e3)}s`);
			await wait(backoff);
			continue;
		}
		if (res.status === 404 && emptyOn404) return [];
		if (!res.ok) throw new Error(`${res.status} ${url}`);
		return res.json();
	}
}
const USER_AGENT = "f1-dashboard-news/1.0 (personal project; summaries with source links)";
async function fetchPage(url) {
	await pageSlot();
	const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
	if (!res.ok) throw new Error(`${res.status} ${url}`);
	return res.text();
}
const openF1Url = (path) => `https://api.openf1.org/v1${path}`;
//#endregion
//#region src/lib/raceFacts.ts
const isClassified = (r) => /^\d+$/.test(r.positionText);
function startLabel(r) {
	return r.grid === 0 ? "the pit lane" : `P${r.grid}`;
}
function startPosition(r, fieldSize) {
	return r.grid === 0 ? fieldSize : r.grid;
}
function resultFacts(race, pole) {
	const facts = [];
	const results = race.results;
	const winner = results.find((r) => r.position === 1);
	if (!winner) return facts;
	const second = results.find((r) => r.position === 2);
	const from = winner.grid === 1 ? "pole" : startLabel(winner);
	const margin = second?.time?.startsWith("+") ? ` by ${second.time.slice(1)}s over ${second.driver.familyName}` : "";
	facts.push(`**${winner.driver.familyName}** won from ${from}${margin}.`);
	if (pole && pole.driver.driverId !== winner.driver.driverId) {
		const poleResult = results.find((r) => r.driver.driverId === pole.driver.driverId);
		if (poleResult) {
			const penalty = poleResult.grid !== 1 ? ` after starting ${startLabel(poleResult)}` : "";
			const finish = isClassified(poleResult) ? `finished P${poleResult.position}` : "did not finish";
			facts.push(`Pole-sitter **${pole.driver.familyName}** ${finish}${penalty}.`);
		}
	}
	const gainer = results.filter(isClassified).map((r) => ({
		r,
		gain: startPosition(r, results.length) - r.position
	})).sort((a, b) => b.gain - a.gain)[0];
	if (gainer && gainer.gain >= 3) facts.push(`Biggest gainer: **${gainer.r.driver.familyName}**, ${startLabel(gainer.r)} → P${gainer.r.position} (+${gainer.gain}).`);
	const retired = results.filter((r) => r.positionText === "R" || r.positionText === "N").sort((a, b) => a.laps - b.laps);
	if (retired.length) facts.push(`Retirements: ${retired.map((r) => `${r.driver.familyName} (lap ${r.laps})`).join(", ")}.`);
	const dns = results.filter((r) => r.positionText === "W");
	if (dns.length) facts.push(`Did not start: ${dns.map((r) => r.driver.familyName).join(", ")}.`);
	const dsq = results.filter((r) => r.positionText === "D");
	if (dsq.length) facts.push(`Disqualified: ${dsq.map((r) => r.driver.familyName).join(", ")}.`);
	return facts;
}
function sessionFacts(race, data) {
	const nameByCode = new Map(race.results.map((r) => [r.driver.code, r.driver.familyName]));
	const codeByNumber = new Map(data.drivers.map((d) => [d.driver_number, d.name_acronym]));
	const nameOf = (code) => nameByCode.get(code) ?? code;
	return [
		neutralisations(data.raceControl),
		penalties(data.raceControl, nameOf),
		strategy(race, data.stints, codeByNumber),
		weatherFact(data.weather),
		data.overtakes.length ? `${data.overtakes.length} overtakes recorded (OpenF1 count, includes pit-cycle position swaps).` : ""
	].filter(Boolean);
}
function neutralisations(messages) {
	const periods = [];
	const add = (lap, text) => periods.push({
		lap,
		text
	});
	let scStart = null;
	let vscStart = null;
	const range = (a, b) => b && b > a ? `laps ${a}–${b}` : `lap ${a}`;
	for (const m of [...messages].sort((a, b) => a.date.localeCompare(b.date))) {
		const lap = m.lap_number ?? 0;
		const msg = m.message;
		if (m.category === "Flag" && m.flag === "RED") add(lap, `red flag lap ${lap}`);
		if (m.category !== "SafetyCar") continue;
		const isVsc = msg.includes("VSC") || msg.includes("VIRTUAL");
		if (msg.includes("DEPLOYED")) if (isVsc) vscStart = lap;
		else scStart = lap;
		else if (isVsc && msg.includes("ENDING") && vscStart !== null) {
			add(vscStart, `VSC ${range(vscStart, lap)}`);
			vscStart = null;
		} else if (!isVsc && msg.includes("IN THIS LAP") && scStart !== null) {
			add(scStart, `safety car ${range(scStart, lap)}`);
			scStart = null;
		}
	}
	if (vscStart !== null) add(vscStart, `VSC lap ${vscStart}`);
	if (scStart !== null) add(scStart, `safety car lap ${scStart}`);
	if (!periods.length) return "No safety car, VSC or red flag.";
	const text = periods.sort((a, b) => a.lap - b.lap).map((p) => p.text).join(" · ");
	return `Neutralisations: ${text.charAt(0).toUpperCase()}${text.slice(1)}.`;
}
const PENALTY = /^FIA STEWARDS: (.+?) PENALTY FOR CAR \d+ \((\w+)\)(?: - (.+?))?(?: \([\d:]+\))?$/;
function penaltyKind(raw) {
	const seconds = raw.match(/^(\d+) SECOND TIME$/);
	if (seconds) return `${seconds[1]}s`;
	if (raw === "DRIVE THROUGH") return "drive-through";
	if (raw.includes("STOP")) return "stop-and-go";
	return raw.toLowerCase();
}
const ACRONYMS = /\b(vsc|sc|drs|fia|pu)\b/g;
function sentenceCase(text) {
	return text.toLowerCase().replace(ACRONYMS, (a) => a.toUpperCase());
}
function penalties(messages, nameOf) {
	const seen = /* @__PURE__ */ new Set();
	const items = [];
	for (const m of messages) {
		const match = m.message.match(PENALTY);
		if (!match || m.message.includes("SERVED")) continue;
		const [, kind, code, reason] = match;
		const text = `${nameOf(code)} ${penaltyKind(kind)}${reason ? ` (${sentenceCase(reason)})` : ""}`;
		if (seen.has(text)) continue;
		seen.add(text);
		items.push(text);
	}
	return items.length ? `Penalties: ${items.join(" · ")}.` : "";
}
const titleCase = (s) => s.charAt(0) + s.slice(1).toLowerCase();
function strategy(race, stints, codeByNumber) {
	if (!stints.length) return "";
	const byCode = /* @__PURE__ */ new Map();
	for (const s of stints) {
		const code = codeByNumber.get(s.driver_number);
		if (!code) continue;
		byCode.set(code, [...byCode.get(code) ?? [], s]);
	}
	const winner = race.results.find((r) => r.position === 1);
	const winnerStints = winner ? (byCode.get(winner.driver.code) ?? []).sort((a, b) => a.stint_number - b.stint_number) : [];
	const stopWord = (n) => `${n} stop${n === 1 ? "" : "s"}`;
	const parts = [];
	if (winnerStints.length) {
		const compounds = winnerStints.map((s) => titleCase(s.compound ?? "Unknown")).join(" → ");
		parts.push(`Winner's strategy: ${compounds} (${stopWord(winnerStints.length - 1)}).`);
	}
	const stopCounts = /* @__PURE__ */ new Map();
	for (const r of race.results.filter(isClassified)) {
		const driverStints = byCode.get(r.driver.code);
		if (!driverStints) continue;
		const stops = driverStints.length - 1;
		stopCounts.set(stops, (stopCounts.get(stops) ?? 0) + 1);
	}
	const words = [
		"no-stop",
		"one-stop",
		"two-stop",
		"three-stop",
		"four-stop"
	];
	const breakdown = [...stopCounts.entries()].sort((a, b) => a[0] - b[0]).map(([stops, count]) => `${count} ${words[stops] ?? `${stops}-stop`}`);
	if (breakdown.length) parts.push(`Finishers: ${breakdown.join(", ")}.`);
	return parts.join(" ");
}
function weatherFact(weather) {
	if (!weather.length) return "";
	const avg = (pick) => Math.round(weather.reduce((sum, w) => sum + pick(w), 0) / weather.length);
	return `${weather.some((w) => w.rainfall > 0) ? "Rain during the race" : "Dry"} · air ${avg((w) => w.air_temperature)}°C · track ${avg((w) => w.track_temperature)}°C.`;
}
//#endregion
//#region src/lib/news.ts
const DAY$1 = 1440 * 60 * 1e3;
function summaryDue(race, now = Date.now()) {
	return now >= Date.parse(`${race.date}T00:00:00Z`) + 2 * DAY$1;
}
//#endregion
//#region scripts/news/sources.ts
const SOURCES = [
	{
		id: "the-race",
		name: "The Race",
		feed: {
			url: "https://www.the-race.com/feed/",
			kind: "rss"
		},
		sitemap: "https://www.the-race.com/sitemap-posts.xml",
		isF1: (url) => url.includes("/formula-1/"),
		summarize: true
	},
	{
		id: "rn365",
		name: "RacingNews365",
		feed: {
			url: "https://racingnews365.com/feed/news.xml",
			kind: "atom"
		},
		isF1: (url) => !/\/(motogp|indycar|formula-e|wec)\b/.test(url),
		summarize: true
	},
	{
		id: "gpfans",
		name: "GPFans",
		feed: {
			url: "https://www.gpfans.com/en/rss.xml",
			kind: "rss"
		},
		isF1: (url) => url.includes("/f1-news/"),
		summarize: true
	},
	{
		id: "planetf1",
		name: "PlanetF1",
		feed: {
			url: "https://www.planetf1.com/rss",
			kind: "rss"
		},
		isF1: () => true,
		summarize: true
	},
	{
		id: "crash",
		name: "Crash.net",
		feed: {
			url: "https://www.crash.net/rss/f1",
			kind: "rss"
		},
		isF1: () => true,
		summarize: false
	}
];
//#endregion
//#region scripts/news/feeds.ts
const decode$1 = (s) => s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, "$1").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, "\"").replace(/&#39;|&#x27;|&apos;/g, "'").trim();
const tag = (block, name) => decode$1(block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`))?.[1] ?? "");
const toIso = (date) => {
	const ms = Date.parse(date);
	return Number.isNaN(ms) ? "" : new Date(ms).toISOString();
};
function parseFeed(xml, source) {
	if (source.feed?.kind === "atom") return [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map(([, entry]) => ({
		source: source.id,
		url: entry.match(/<link[^>]*rel="alternate"[^>]*href="([^"]+)"/)?.[1] ?? entry.match(/<link[^>]*href="([^"]+)"/)?.[1] ?? "",
		title: tag(entry, "title"),
		published: toIso(tag(entry, "published") || tag(entry, "updated"))
	}));
	return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].map(([, item]) => ({
		source: source.id,
		url: tag(item, "link"),
		title: tag(item, "title"),
		published: toIso(tag(item, "pubDate"))
	}));
}
function parseSitemap(xml, source) {
	return [...xml.matchAll(/<url>([\s\S]*?)<\/url>/g)].map(([, entry]) => {
		const url = tag(entry, "loc");
		const slug = url.split("/").filter(Boolean).pop() ?? "";
		return {
			source: source.id,
			url,
			title: slug.replace(/-/g, " "),
			published: toIso(tag(entry, "lastmod"))
		};
	});
}
//#endregion
//#region scripts/news/extract.ts
const decode = (s) => s.replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, "\"").replace(/&#39;|&#x27;|&apos;|&rsquo;|&lsquo;/g, "'").replace(/&ldquo;|&rdquo;/g, "\"").replace(/&ndash;/g, "–").replace(/&mdash;/g, "—").replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)));
const CHROME = /<(script|style|noscript|svg|nav|header|footer|aside|form|figure|iframe)\b[\s\S]*?<\/\1>/gi;
function isProse(p) {
	const words = p.split(/\s+/).length;
	const letters = (p.match(/[A-Za-z]/g) ?? []).length;
	return p.length >= 60 && words >= 10 && letters / p.length > .7 && !/[{};]|function\(|var /.test(p);
}
function extractArticle(html) {
	const title = decode(html.match(/<meta[^>]+property="og:title"[^>]+content="([^"]+)"/)?.[1] ?? html.match(/<title>([^<]+)<\/title>/)?.[1] ?? "").trim();
	const published = html.match(/"datePublished"\s*:\s*"([^"]+)"/)?.[1] ?? html.match(/<meta[^>]+property="article:published_time"[^>]+content="([^"]+)"/)?.[1] ?? "";
	let body = html.replace(CHROME, " ");
	const articles = [...body.matchAll(/<article\b[\s\S]*?<\/article>/gi)].map((m) => m[0]);
	if (articles.length) body = articles.sort((a, b) => b.length - a.length)[0];
	const paragraphs = [...body.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)].map((m) => decode(m[1].replace(/<[^>]+>/g, "")).replace(/\s+/g, " ").trim()).filter(isProse);
	return {
		title,
		published,
		text: [...new Set(paragraphs)].join("\n\n")
	};
}
//#endregion
//#region scripts/news/robots.ts
const rules = /* @__PURE__ */ new Map();
async function disallowed(origin, fetchText) {
	if (rules.has(origin)) return rules.get(origin);
	let paths = [];
	try {
		const txt = await fetchText(`${origin}/robots.txt`);
		let applies = false;
		for (const raw of txt.split(/\r?\n/)) {
			const [key, ...rest] = raw.split("#")[0].trim().split(":");
			const value = rest.join(":").trim();
			if (/^user-agent$/i.test(key)) applies = value === "*";
			else if (applies && /^disallow$/i.test(key) && value) paths.push(value);
		}
	} catch {
		paths = [];
	}
	rules.set(origin, paths);
	return paths;
}
async function allowedByRobots(url, fetchText) {
	const { origin, pathname } = new URL(url);
	return !(await disallowed(origin, fetchText)).some((prefix) => pathname.startsWith(prefix));
}
//#endregion
//#region scripts/news/summarize.ts
const MODEL = "claude-sonnet-5";
const SCHEMA = {
	type: "object",
	properties: {
		headline: {
			type: "string",
			description: "One sentence capturing the story of the weekend"
		},
		bullets: {
			type: "array",
			description: "5 to 8 storylines, most important first",
			items: {
				type: "object",
				properties: {
					text: {
						type: "string",
						description: "One or two sentences. Wrap the key driver/team name in **double asterisks**."
					},
					sources: {
						type: "array",
						items: { type: "integer" },
						description: "Ids of the articles this bullet draws on"
					}
				},
				required: ["text", "sources"],
				additionalProperties: false
			}
		},
		quotes: {
			type: "array",
			description: "Up to 4 short quotes from drivers or team members, copied exactly from an article",
			items: {
				type: "object",
				properties: {
					speaker: { type: "string" },
					quote: { type: "string" },
					source: { type: "integer" }
				},
				required: [
					"speaker",
					"quote",
					"source"
				],
				additionalProperties: false
			}
		}
	},
	required: [
		"headline",
		"bullets",
		"quotes"
	],
	additionalProperties: false
};
const SYSTEM = `You write the race-weekend notes for a Formula 1 season dashboard.

You receive two things:
1. DATA: the official classification and timing facts for the weekend. This is authoritative. Every number, position, lap count, gap and penalty you write must agree with DATA. If an article disagrees with DATA, DATA is right.
2. ARTICLES: press coverage of the weekend, each with an id.

Write the storylines the data alone can't tell: why things happened, turning points, team and driver reactions, strategy calls, controversies, and off-track news from the weekend (appeals, upgrades, contracts, regulation disputes). Don't restate the classification line by line; the dashboard already shows it.

Rules:
- Every bullet cites the article ids it draws on. Only say what the articles or DATA support.
- Write in your own words. Don't copy sentences from the articles; the only verbatim text allowed is in "quotes".
- Quotes must be copied exactly, character for character, from an article, and must be something a driver, team principal or team member said. Skip quotes rather than paraphrase them.
- Neutral, factual tone. No speculation beyond what the articles report.`;
function formatArticles(articles, maxCharsEach) {
	return articles.map((a) => `<article id="${a.id}" site="${a.site}" published="${a.published}">
<title>${a.title}</title>
${a.text.slice(0, maxCharsEach)}
</article>`).join("\n\n");
}
const normalise = (s) => s.replace(/[“”„]/g, "\"").replace(/[‘’]/g, "'").replace(/\s+/g, " ").trim().toLowerCase();
async function summarizeWeekend(client, data, articles) {
	const response = await client.messages.create({
		model: MODEL,
		max_tokens: 16e3,
		system: SYSTEM,
		output_config: { format: {
			type: "json_schema",
			schema: SCHEMA
		} },
		messages: [{
			role: "user",
			content: `<data>\n${data}\n</data>\n\n<articles>\n${formatArticles(articles, 12e3)}\n</articles>`
		}]
	});
	if (response.stop_reason === "refusal") throw new Error(`Summary refused: ${response.stop_details?.category ?? "unknown"}`);
	if (response.stop_reason === "max_tokens") throw new Error("Summary hit max_tokens");
	const text = response.content.flatMap((b) => b.type === "text" ? [b.text] : []).join("");
	const summary = JSON.parse(text);
	const byId = new Map(articles.map((a) => [a.id, a]));
	return {
		headline: summary.headline,
		bullets: summary.bullets.map((b) => ({
			text: b.text,
			sources: b.sources.filter((id) => byId.has(id))
		})).filter((b) => b.sources.length > 0),
		quotes: summary.quotes.filter((q) => {
			const article = byId.get(q.source);
			return article !== void 0 && normalise(article.text).includes(normalise(q.quote));
		})
	};
}
//#endregion
//#region scripts/news/pipeline.ts
const DAY = 1440 * 60 * 1e3;
const MAX_ARTICLES = 14;
const MAX_PER_SITE = {
	several: 5,
	single: 8
};
const MIN_ARTICLE_CHARS = 800;
const MAX_LINKS = 6;
async function loadSeason(deps, season) {
	const [schedule, races, sprints, poles, meetings, sessions] = await Promise.all([
		fetchSchedule(season),
		fetchAllRaces(season),
		fetchAllSprints(season),
		fetchPoles(season),
		deps.openF1(`/meetings?year=${season}`),
		deps.openF1(`/sessions?year=${season}`)
	]);
	return {
		season,
		schedule,
		races,
		sprints,
		poles,
		meetings,
		sessions
	};
}
function weekendWindow(race) {
	return [Date.parse(`${race.firstPracticeDate ?? race.date}T00:00:00Z`) - DAY, Date.parse(`${race.date}T00:00:00Z`) + 4 * DAY];
}
const STOP_WORDS = new Set([
	"grand",
	"prix",
	"the",
	"of",
	"in",
	"circuit",
	"international"
]);
const WEEKEND_WORDS = [
	"race",
	"qualifying",
	"sprint",
	"pole",
	"wins",
	"win",
	"victory",
	"podium",
	"penalty",
	"crash",
	"strategy",
	"result",
	"report",
	"verdict",
	"winners",
	"losers",
	"ratings"
];
function relevance(listing, race) {
	const text = `${listing.title} ${listing.url}`.toLowerCase();
	const eventWords = [
		race.raceName,
		race.circuitName,
		race.locality,
		race.country
	].join(" ").toLowerCase().split(/[^a-zà-ÿ]+/).filter((w) => w.length > 2 && !STOP_WORDS.has(w));
	let score = 0;
	for (const w of new Set(eventWords)) if (text.includes(w)) score += 3;
	for (const w of WEEKEND_WORDS) if (text.includes(w)) score += 1;
	return score;
}
function pickForWeekend(listings, race, sources, limit) {
	const [from, to] = weekendWindow(race);
	const bySite = /* @__PURE__ */ new Map();
	const seen = /* @__PURE__ */ new Set();
	const inWindow = listings.filter((l) => {
		const source = sources.find((s) => s.id === l.source);
		const at = Date.parse(l.published);
		return source !== void 0 && source.isF1(l.url) && at >= from && at <= to;
	});
	const perSite = new Set(inWindow.map((l) => l.source)).size > 1 ? MAX_PER_SITE.several : MAX_PER_SITE.single;
	return inWindow.map((l) => ({
		l,
		score: relevance(l, race)
	})).filter((x) => x.score > 0).sort((a, b) => b.score - a.score).map((x) => x.l).filter((l) => {
		if (seen.has(l.url)) return false;
		const count = bySite.get(l.source) ?? 0;
		if (count >= perSite) return false;
		seen.add(l.url);
		bySite.set(l.source, count + 1);
		return true;
	}).slice(0, limit);
}
async function collectListings(deps, oldestNeeded) {
	const listings = [];
	for (const source of SOURCES) {
		if (!source.feed) continue;
		try {
			const items = parseFeed(await deps.page(source.feed.url, true), source);
			listings.push(...items);
			const oldest = Math.min(...items.map((i) => Date.parse(i.published)).filter(Number.isFinite));
			if (source.sitemap && oldest > oldestNeeded) listings.push(...parseSitemap(await deps.page(source.sitemap, true), source));
		} catch (err) {
			deps.log(`  ${source.name}: ${err.message}`);
		}
	}
	return listings;
}
async function fetchArticles(deps, picks) {
	const articles = [];
	const robotsText = (url) => deps.page(url, true);
	for (const pick of picks) {
		if (!await allowedByRobots(pick.url, robotsText)) continue;
		try {
			const article = extractArticle(await deps.page(pick.url));
			if (article.text.length < MIN_ARTICLE_CHARS) continue;
			articles.push({
				id: articles.length + 1,
				site: SOURCES.find((s) => s.id === pick.source).name,
				title: article.title || pick.title,
				url: pick.url,
				published: (article.published || pick.published).slice(0, 10),
				text: article.text
			});
		} catch (err) {
			deps.log(`  skipped ${pick.url}: ${err.message}`);
		}
	}
	return articles;
}
function classification(race) {
	return race.results.map((r) => {
		const pos = /^\d+$/.test(r.positionText) ? `P${r.position}` : {
			R: "DNF",
			W: "DNS",
			D: "DSQ",
			N: "NC"
		}[r.positionText] ?? r.positionText;
		const extra = r.positionText === "R" ? ` (retired lap ${r.laps}, ${r.status})` : r.time ? ` (${r.time})` : "";
		return `${pos} ${r.driver.givenName} ${r.driver.familyName} (${r.constructor.name}) grid ${r.grid === 0 ? "pit lane" : r.grid}${extra}`;
	}).join("\n");
}
async function buildData(deps, data, info, race) {
	const pole = data.poles.find((p) => p.round === race.round);
	const sprint = data.sprints.find((s) => s.round === race.round && s.results.length > 0);
	const meeting = data.meetings.find((m) => !m.is_cancelled && m.date_start.slice(0, 10) <= race.date && race.date <= m.date_end.slice(0, 10));
	const raceSession = data.sessions.find((s) => s.meeting_key === meeting?.meeting_key && s.session_name === "Race");
	let facts = resultFacts(race, pole);
	if (raceSession) {
		const key = raceSession.session_key;
		const sessionData = {
			drivers: await deps.openF1(`/drivers?session_key=${key}`),
			raceControl: await deps.openF1(`/race_control?session_key=${key}`),
			stints: await deps.openF1(`/stints?session_key=${key}`),
			weather: await deps.openF1(`/weather?session_key=${key}`),
			overtakes: await deps.openF1(`/overtakes?session_key=${key}`)
		};
		facts = [...facts, ...sessionFacts(race, sessionData)];
	}
	const [drivers, constructors] = await Promise.all([fetchDriverStandings(data.season, race.round), fetchConstructorStandings(data.season, race.round)]);
	return [
		`Round ${race.round}: ${race.raceName}, ${info.circuitName} (${info.locality}, ${info.country}), race day ${race.date}`,
		pole ? `Pole: ${pole.driver.givenName} ${pole.driver.familyName} (${pole.constructor.name})` : "",
		`\nRace classification:\n${classification(race)}`,
		sprint ? `\nSprint classification:\n${classification(sprint)}` : "",
		`\nFacts:\n${facts.map((f) => `- ${f.replace(/\*\*/g, "")}`).join("\n")}`,
		`\nDrivers' championship after this round: ${drivers.slice(0, 6).map((d) => `${d.driver.familyName} ${d.points}`).join(", ")}`,
		`Constructors' championship after this round: ${constructors.slice(0, 6).map((c) => `${c.constructor.name} ${c.points}`).join(", ")}`
	].filter(Boolean).join("\n");
}
async function prepareWeekend(deps, data, round, listings) {
	const race = data.races.find((r) => r.round === round);
	const info = data.schedule.find((r) => r.round === round);
	if (!race || !info) throw new Error(`Round ${round} has no results yet`);
	const summarizable = SOURCES.filter((s) => s.summarize);
	const linkOnly = SOURCES.filter((s) => !s.summarize);
	return {
		articles: await fetchArticles(deps, pickForWeekend(listings, info, summarizable, MAX_ARTICLES)),
		links: pickForWeekend(listings, info, linkOnly, MAX_LINKS).map((l) => ({
			site: linkOnly.find((s) => s.id === l.source).name,
			title: l.title,
			url: l.url,
			published: l.published.slice(0, 10)
		})),
		data: await buildData(deps, data, info, race)
	};
}
async function summarizeRound(client, inputs) {
	return {
		...await summarizeWeekend(client, inputs.data, inputs.articles),
		generatedAt: (/* @__PURE__ */ new Date()).toISOString(),
		model: MODEL,
		sources: inputs.articles.map(({ id, site, title, url, published }) => ({
			id,
			site,
			title,
			url,
			published
		})),
		links: inputs.links
	};
}
//#endregion
//#region server/news.ts
const seed = raceNews_default;
const MAX_ATTEMPTS = 3;
const RETRY_AFTER_MS = 720 * 60 * 1e3;
const LOCK_MS = 600 * 1e3;
const blobPath = (season) => `race-news/${season}.json`;
async function readStored(season) {
	const blob = await get(blobPath(season), { access: "private" });
	if (!blob || blob.statusCode !== 200) return {
		rounds: {},
		attempts: {}
	};
	return await new Response(blob.stream).json();
}
async function writeStored(season, stored) {
	await put(blobPath(season), JSON.stringify(stored), {
		access: "private",
		addRandomSuffix: false,
		allowOverwrite: true,
		contentType: "application/json"
	});
}
const deps = {
	page: (url) => fetchPage(url),
	openF1: (path) => fetchJson(openF1Url(path), true),
	log: (message) => console.log(message)
};
async function dueRound(season, stored, now) {
	const seeded = Object.keys(seed[season] ?? {}).map(Number);
	const firstAuto = seeded.length ? Math.max(...seeded) + 1 : 1;
	return (await fetchSchedule(season)).filter((r) => r.round >= firstAuto && summaryDue(r, now)).filter((r) => !stored.rounds[r.round] && !seed[season]?.[r.round]).filter((r) => {
		const attempt = stored.attempts[r.round];
		return !attempt || attempt.count < MAX_ATTEMPTS && now - Date.parse(attempt.last) > RETRY_AFTER_MS;
	}).map((r) => r.round)[0];
}
async function generate(season, round) {
	const recordFailure = async (reason) => {
		const latest = await readStored(season);
		const previous = latest.attempts[round];
		latest.attempts[round] = {
			count: (previous?.count ?? 0) + 1,
			last: (/* @__PURE__ */ new Date()).toISOString(),
			reason
		};
		delete latest.lock;
		await writeStored(season, latest);
		console.warn(`R${round}: ${reason}`);
	};
	try {
		const data = await loadSeason(deps, season);
		if (!data.races.some((r) => r.round === round && r.results.length > 0)) return await recordFailure("no results yet");
		const inputs = await prepareWeekend(deps, data, round, await collectListings(deps, weekendWindow(data.schedule.find((r) => r.round === round))[0]));
		if (inputs.articles.length < 2) return await recordFailure(`only ${inputs.articles.length} articles found`);
		const news = await summarizeRound(new Anthropic(), inputs);
		const latest = await readStored(season);
		latest.rounds[round] = news;
		delete latest.attempts[round];
		delete latest.lock;
		await writeStored(season, latest);
		console.log(`R${round}: summarized ${inputs.articles.length} articles`);
	} catch (err) {
		await recordFailure(err.message);
	}
}
async function GET(request) {
	const url = new URL(request.url);
	const currentYear = (/* @__PURE__ */ new Date()).getFullYear();
	const season = Number(url.searchParams.get("season") ?? currentYear);
	if (!Number.isInteger(season) || season < 2023 || season > currentYear) return Response.json({ error: "season must be between 2023 and the current year" }, { status: 400 });
	const stored = await readStored(season);
	const now = Date.now();
	let generating = null;
	if (stored.lock && now - Date.parse(stored.lock.startedAt) < LOCK_MS) generating = stored.lock.round;
	else {
		const round = await dueRound(season, stored, now);
		if (round !== void 0) {
			stored.lock = {
				round,
				startedAt: new Date(now).toISOString()
			};
			await writeStored(season, stored);
			generating = round;
			waitUntil(generate(season, round));
		}
	}
	return Response.json({
		season,
		rounds: {
			...seed[season],
			...stored.rounds
		},
		generating
	}, { headers: { "Cache-Control": "no-store" } });
}
//#endregion
export { GET };
