// GENERATED by `npm run build:api` from server/*.ts — do not edit.
import { a as openF1Url, i as jolpicaUrl, n as fetchJson } from "./_chunks/http.js";
import { get, put } from "@vercel/blob";
import { waitUntil } from "@vercel/functions";
//#region src/data/paceRatings.json
var paceRatings_default = { "2026": {
	"generatedAt": "2026-09-24T15:24:10.826Z",
	"rounds": {
		"1": {
			"raceName": "Australian Grand Prix",
			"gaps": {
				"quali": {
					"audi": 2.169,
					"williams": 3.086,
					"haas": 2.284,
					"alpine": 2.526,
					"rb": 1.851,
					"aston_martin": 4.395,
					"cadillac": 5.205,
					"mclaren": 1.098,
					"ferrari": 1.03,
					"mercedes": 0,
					"red_bull": 1
				},
				"race": {
					"red_bull": .723,
					"rb": 1.841,
					"mclaren": .98,
					"mercedes": 0,
					"haas": 2.058,
					"alpine": 2.67,
					"aston_martin": 4.182,
					"audi": 2.034,
					"williams": 2.769,
					"cadillac": 4.576,
					"ferrari": .056
				},
				"straight": {
					"audi": 1.954,
					"williams": 4.235,
					"haas": 3.909,
					"alpine": 2.932,
					"rb": 3.583,
					"aston_martin": 6.189,
					"cadillac": 3.257,
					"mclaren": 4.235,
					"ferrari": .326,
					"mercedes": .651,
					"red_bull": 0
				},
				"slowCorners": {
					"audi": 2.575,
					"williams": 3.593,
					"haas": 2.499,
					"alpine": 3.877,
					"rb": 3.029,
					"aston_martin": 3.533,
					"cadillac": 7.811,
					"mclaren": 2.25,
					"ferrari": 0,
					"mercedes": 2.397,
					"red_bull": 1.765
				},
				"highCorners": {
					"audi": 2.505,
					"williams": 6.298,
					"haas": 2.326,
					"alpine": 4.428,
					"rb": 4.431,
					"aston_martin": 7.242,
					"cadillac": 8.722,
					"mclaren": 1.662,
					"ferrari": .071,
					"mercedes": 0,
					"red_bull": 3.629
				},
				"aero": {
					"audi": 2.032,
					"williams": 5.068,
					"haas": 2.919,
					"alpine": 3.481,
					"rb": 3.809,
					"aston_martin": 6.517,
					"cadillac": 5.791,
					"mclaren": 2.75,
					"ferrari": 0,
					"mercedes": .127,
					"red_bull": 1.616
				}
			},
			"corners": {
				"slow": 3,
				"medium": 1,
				"high": 2
			},
			"sessions": {
				"qualifying": 11230,
				"race": 11234
			}
		},
		"2": {
			"raceName": "Chinese Grand Prix",
			"gaps": {
				"quali": {
					"cadillac": 3.663,
					"alpine": .879,
					"williams": 2.447,
					"rb": 1.848,
					"aston_martin": 3.41,
					"red_bull": 1.019,
					"ferrari": .381,
					"haas": 1.231,
					"mclaren": .528,
					"audi": 1.401,
					"mercedes": 0
				},
				"race": {
					"ferrari": .611,
					"mercedes": 0,
					"alpine": 1.363,
					"rb": 1.983,
					"haas": 1.578,
					"aston_martin": 3.764,
					"williams": 2.713,
					"red_bull": 1.693,
					"cadillac": 3.588,
					"audi": 1.946
				},
				"straight": {
					"cadillac": 5.31,
					"alpine": 2.065,
					"williams": 0,
					"rb": 5.015,
					"aston_martin": 6.49,
					"red_bull": 3.245,
					"ferrari": 5.605,
					"haas": 3.245,
					"mclaren": 8.85,
					"audi": .885,
					"mercedes": 4.13
				},
				"slowCorners": {
					"cadillac": 2.486,
					"alpine": 5.982,
					"williams": 8.774,
					"rb": 7.707,
					"aston_martin": 7.151,
					"ferrari": 3.758,
					"haas": 3.459,
					"mclaren": 4.809,
					"audi": 3.786,
					"mercedes": 5.264,
					"red_bull": 0
				},
				"highCorners": {
					"alpine": 6.379,
					"williams": 3.815,
					"rb": 0,
					"aston_martin": 6.201,
					"ferrari": 4.606,
					"haas": 8.359,
					"mclaren": 6.04,
					"audi": 1.06,
					"mercedes": 4.079
				},
				"aero": {
					"alpine": 3.249,
					"williams": .935,
					"rb": 1.535,
					"aston_martin": 5.373,
					"ferrari": 4.133,
					"haas": 4.829,
					"mclaren": 6.472,
					"audi": 0,
					"mercedes": 3.132
				}
			},
			"corners": {
				"slow": 5,
				"medium": 1,
				"high": 1
			},
			"sessions": {
				"qualifying": 11241,
				"race": 11245
			}
		},
		"3": {
			"raceName": "Japanese Grand Prix",
			"gaps": {
				"quali": {
					"rb": 1.499,
					"aston_martin": 4.357,
					"haas": 1.725,
					"cadillac": 3.861,
					"williams": 2.421,
					"mclaren": .399,
					"audi": 1.365,
					"ferrari": .591,
					"red_bull": 1.352,
					"alpine": 1.028,
					"mercedes": 0
				},
				"race": {
					"mclaren": .446,
					"ferrari": .475,
					"mercedes": 0,
					"alpine": 1.163,
					"red_bull": 1.109,
					"rb": 1.887,
					"haas": 1.929,
					"audi": 1.783,
					"williams": 2.353,
					"cadillac": 3.505,
					"aston_martin": 4.376
				},
				"straight": {
					"rb": 1.351,
					"aston_martin": 5.068,
					"haas": 1.014,
					"cadillac": 1.689,
					"williams": 1.014,
					"mclaren": 2.703,
					"audi": .676,
					"ferrari": 2.027,
					"red_bull": .338,
					"alpine": 0,
					"mercedes": 1.351
				},
				"slowCorners": {
					"rb": 12.868,
					"aston_martin": 7.306,
					"cadillac": 4.784,
					"williams": 4.201,
					"mclaren": 5.317,
					"ferrari": 0,
					"red_bull": 11.155,
					"alpine": 3.709
				},
				"highCorners": {
					"rb": 2.988,
					"aston_martin": 7.478,
					"haas": 3.412,
					"cadillac": 7.509,
					"williams": 6.095,
					"mclaren": 0,
					"audi": 1.659,
					"ferrari": .643,
					"red_bull": 1.537,
					"alpine": 1.382,
					"mercedes": .886
				},
				"aero": {
					"rb": 1.479,
					"aston_martin": 5.582,
					"haas": 1.522,
					"cadillac": 3.908,
					"williams": 2.863,
					"mclaren": .66,
					"audi": .477,
					"ferrari": .644,
					"red_bull": .247,
					"alpine": 0,
					"mercedes": .428
				}
			},
			"corners": {
				"slow": 1,
				"medium": 4,
				"high": 2
			},
			"sessions": {
				"qualifying": 11249,
				"race": 11253
			}
		},
		"4": {
			"raceName": "Miami Grand Prix",
			"gaps": {
				"quali": {
					"cadillac": 4.363,
					"haas": 1.756,
					"rb": 1.937,
					"aston_martin": 3.759,
					"williams": 1.984,
					"audi": 1.869,
					"red_bull": .189,
					"ferrari": .393,
					"mclaren": .439,
					"alpine": 1.098,
					"mercedes": 0
				},
				"race": {
					"ferrari": .629,
					"mercedes": .011,
					"mclaren": 0,
					"alpine": 1.416,
					"rb": 2.874,
					"red_bull": 1.208,
					"williams": 1.867,
					"haas": 2.164,
					"aston_martin": 3.412,
					"cadillac": 3.742,
					"audi": 2.341
				},
				"straight": {
					"cadillac": 5.556,
					"haas": .617,
					"rb": 2.16,
					"aston_martin": 5.247,
					"williams": .926,
					"audi": 3.086,
					"red_bull": .309,
					"ferrari": 1.235,
					"mclaren": .926,
					"alpine": .309,
					"mercedes": 0
				},
				"slowCorners": {
					"cadillac": 5.876,
					"haas": 2.812,
					"rb": 3.634,
					"aston_martin": 4.427,
					"williams": 2.351,
					"audi": 3.561,
					"red_bull": .784,
					"ferrari": .548,
					"mclaren": .466,
					"alpine": 3.515,
					"mercedes": 0
				},
				"highCorners": {},
				"aero": {}
			},
			"corners": {
				"slow": 4,
				"medium": 1,
				"high": 0
			},
			"sessions": {
				"qualifying": 11276,
				"race": 11280
			}
		},
		"5": {
			"raceName": "Canadian Grand Prix",
			"gaps": {
				"quali": {
					"williams": 2.335,
					"rb": .967,
					"haas": 2.532,
					"alpine": 1.542,
					"cadillac": 3.928,
					"aston_martin": 3.607,
					"mclaren": .208,
					"audi": 1.802,
					"mercedes": 0,
					"ferrari": .4,
					"red_bull": .453
				},
				"race": {
					"mercedes": 0,
					"ferrari": .335,
					"red_bull": .415,
					"alpine": 1.942,
					"rb": 2.476,
					"haas": 2.478,
					"aston_martin": 5.511,
					"williams": 2.102,
					"mclaren": 1.557,
					"audi": 2.336,
					"cadillac": 3.99
				},
				"straight": {
					"williams": 2.769,
					"rb": 1.538,
					"haas": 1.231,
					"alpine": 1.538,
					"cadillac": 3.385,
					"aston_martin": 3.385,
					"mclaren": 2.462,
					"audi": 1.846,
					"mercedes": 0,
					"ferrari": .615,
					"red_bull": 1.846
				},
				"slowCorners": {
					"williams": 3.647,
					"rb": 2.15,
					"haas": 2.695,
					"alpine": 3.246,
					"cadillac": 3.991,
					"aston_martin": 3.337,
					"mclaren": 2.156,
					"audi": 3.293,
					"mercedes": 1.875,
					"ferrari": 0,
					"red_bull": 1.092
				},
				"highCorners": {},
				"aero": {}
			},
			"corners": {
				"slow": 3,
				"medium": 3,
				"high": 0
			},
			"sessions": {
				"qualifying": 11287,
				"race": 11291
			}
		},
		"6": {
			"raceName": "Monaco Grand Prix",
			"gaps": {
				"quali": {
					"cadillac": 3.742,
					"alpine": 1.631,
					"haas": 3.707,
					"audi": 2.569,
					"rb": 1.889,
					"williams": 2.409,
					"aston_martin": 4.577,
					"red_bull": .06,
					"mclaren": .795,
					"ferrari": .316,
					"mercedes": 0
				},
				"race": {
					"mercedes": 0,
					"ferrari": .45,
					"red_bull": 2.434,
					"mclaren": 2.17,
					"alpine": 2.625,
					"rb": 2.878,
					"williams": 3.486,
					"audi": 3.238,
					"cadillac": 4.574,
					"haas": 4.321,
					"aston_martin": 3.721
				},
				"straight": {
					"cadillac": 1.767,
					"alpine": .707,
					"haas": 1.06,
					"audi": 0,
					"rb": .707,
					"williams": 1.413,
					"aston_martin": 4.594,
					"red_bull": .707,
					"mclaren": 1.06,
					"ferrari": 1.413,
					"mercedes": .707
				},
				"slowCorners": {
					"cadillac": 6.439,
					"alpine": 3.816,
					"haas": 5.805,
					"audi": 4.539,
					"rb": 4.111,
					"williams": 5.237,
					"aston_martin": 5.969,
					"red_bull": 0,
					"mclaren": 3.679,
					"ferrari": 2.327,
					"mercedes": 2.47
				},
				"highCorners": {},
				"aero": {}
			},
			"corners": {
				"slow": 7,
				"medium": 2,
				"high": 0
			},
			"sessions": {
				"qualifying": 11295,
				"race": 11299
			}
		},
		"7": {
			"raceName": "Barcelona Grand Prix",
			"gaps": {
				"quali": {
					"cadillac": 3.838,
					"haas": 2.29,
					"williams": 2.949,
					"aston_martin": 5.462,
					"audi": 1.458,
					"red_bull": .458,
					"alpine": 2.025,
					"ferrari": .086,
					"mercedes": 0,
					"rb": 1.213,
					"mclaren": .431
				},
				"race": {
					"mercedes": .433,
					"ferrari": 0,
					"mclaren": .833,
					"red_bull": .814,
					"rb": 2.933,
					"audi": 3.044,
					"alpine": 3.001,
					"williams": 3.484,
					"haas": 3.754,
					"cadillac": 4.857,
					"aston_martin": 5.692
				},
				"straight": {
					"cadillac": 2.011,
					"haas": .862,
					"williams": 2.586,
					"aston_martin": 3.448,
					"audi": 0,
					"red_bull": 3.161,
					"alpine": 0,
					"ferrari": 4.31,
					"mercedes": 1.437,
					"rb": 3.161,
					"mclaren": 3.161
				},
				"slowCorners": {
					"cadillac": 4.732,
					"haas": 1.587,
					"williams": 2.33,
					"aston_martin": 3.676,
					"audi": 1.736,
					"red_bull": 1.773,
					"alpine": 1.737,
					"ferrari": 0,
					"mercedes": .425,
					"rb": 1.864,
					"mclaren": .531
				},
				"highCorners": {
					"cadillac": 7.665,
					"haas": 3.79,
					"williams": 5.112,
					"aston_martin": 8.551,
					"audi": .763,
					"red_bull": .738,
					"alpine": 2.418,
					"ferrari": .009,
					"mercedes": .602,
					"rb": 1.537,
					"mclaren": 0
				},
				"aero": {
					"cadillac": 4.457,
					"haas": 1.944,
					"williams": 3.468,
					"aston_martin": 5.618,
					"audi": 0,
					"red_bull": 1.568,
					"alpine": .827,
					"ferrari": 1.778,
					"mercedes": .638,
					"rb": 1.967,
					"mclaren": 1.199
				}
			},
			"corners": {
				"slow": 3,
				"medium": 3,
				"high": 2
			},
			"sessions": {
				"qualifying": 11303,
				"race": 11307
			}
		},
		"8": {
			"raceName": "Austrian Grand Prix",
			"gaps": {
				"quali": {
					"haas": 2.133,
					"cadillac": 4.284,
					"williams": 3.235,
					"audi": 1.785,
					"aston_martin": 5.792,
					"mercedes": 0,
					"red_bull": .548,
					"mclaren": .588,
					"ferrari": .357,
					"alpine": 1.679,
					"rb": 1.274
				},
				"race": {
					"mercedes": 0,
					"ferrari": .501,
					"red_bull": .401,
					"mclaren": .845,
					"rb": 2.056,
					"audi": 2.145,
					"haas": 3.352,
					"alpine": 2.455,
					"williams": 3.63,
					"aston_martin": 4.517
				},
				"straight": {
					"haas": 3.175,
					"cadillac": 1.587,
					"williams": .317,
					"audi": 2.222,
					"aston_martin": 6.984,
					"mercedes": 0,
					"red_bull": 1.27,
					"mclaren": .952,
					"ferrari": 3.175,
					"alpine": 0,
					"rb": 1.905
				},
				"slowCorners": {
					"haas": 3.741,
					"cadillac": 3.253,
					"williams": 4.358,
					"audi": 2.507,
					"aston_martin": 5.534,
					"mercedes": 1.001,
					"red_bull": 1.992,
					"mclaren": .286,
					"ferrari": 0,
					"alpine": 2.107,
					"rb": 2.774
				},
				"highCorners": {
					"haas": 4.802,
					"cadillac": 8.229,
					"williams": 5.831,
					"audi": 2.439,
					"aston_martin": 9.516,
					"mercedes": .6,
					"red_bull": 1.399,
					"mclaren": 2.019,
					"ferrari": 0,
					"alpine": 4.724,
					"rb": 2.129
				},
				"aero": {
					"haas": 3.688,
					"cadillac": 4.608,
					"williams": 2.774,
					"audi": 2.03,
					"aston_martin": 7.95,
					"mercedes": 0,
					"red_bull": 1.034,
					"mclaren": 1.185,
					"ferrari": 1.287,
					"alpine": 2.062,
					"rb": 1.717
				}
			},
			"corners": {
				"slow": 2,
				"medium": 2,
				"high": 3
			},
			"sessions": {
				"qualifying": 11311,
				"race": 11315
			}
		},
		"9": {
			"raceName": "British Grand Prix",
			"gaps": {
				"quali": {
					"cadillac": 3.536,
					"williams": 2.782,
					"haas": 2.712,
					"aston_martin": 5.393,
					"rb": 1.349,
					"audi": 1.532,
					"ferrari": .199,
					"mclaren": .869,
					"red_bull": .721,
					"alpine": 2.215,
					"mercedes": 0
				},
				"race": {
					"ferrari": 0,
					"mercedes": .177,
					"red_bull": .597,
					"mclaren": .86,
					"rb": 1.649,
					"williams": 2.784,
					"haas": 2.87,
					"alpine": 2.107,
					"audi": 1.854,
					"cadillac": 3.39,
					"aston_martin": 5.05
				},
				"straight": {
					"cadillac": 5.215,
					"williams": 5.215,
					"haas": 2.454,
					"aston_martin": 5.828,
					"rb": 5.828,
					"audi": 4.908,
					"ferrari": 2.761,
					"mclaren": 5.521,
					"red_bull": 3.988,
					"alpine": 0,
					"mercedes": 4.294
				},
				"slowCorners": {
					"cadillac": 5.801,
					"williams": 5.469,
					"haas": 5.363,
					"aston_martin": 7.213,
					"rb": 3.063,
					"audi": 3.577,
					"ferrari": 0,
					"mclaren": 3.829,
					"red_bull": 2.854,
					"alpine": 5.624,
					"mercedes": 2.75
				},
				"highCorners": {
					"cadillac": 9.699,
					"williams": 6.797,
					"haas": 5.725,
					"aston_martin": 9.987,
					"rb": 4.651,
					"audi": 3.473,
					"ferrari": 1.58,
					"mclaren": 2.339,
					"red_bull": 2.417,
					"alpine": 5.805,
					"mercedes": 0
				},
				"aero": {
					"cadillac": 5.31,
					"williams": 3.859,
					"haas": 1.942,
					"aston_martin": 5.76,
					"rb": 3.092,
					"audi": 2.043,
					"ferrari": .023,
					"mclaren": 1.783,
					"red_bull": 1.055,
					"alpine": .755,
					"mercedes": 0
				}
			},
			"corners": {
				"slow": 3,
				"medium": 0,
				"high": 3
			},
			"sessions": {
				"qualifying": 11322,
				"race": 11326
			}
		},
		"10": {
			"raceName": "Belgian Grand Prix",
			"gaps": {
				"quali": {
					"aston_martin": 5.405,
					"cadillac": 3.317,
					"alpine": 1.888,
					"red_bull": .304,
					"mercedes": 0,
					"haas": 2.317,
					"rb": .749,
					"williams": 2.315,
					"ferrari": .51,
					"audi": 1.214,
					"mclaren": .422
				},
				"race": {
					"mercedes": .199,
					"ferrari": .291,
					"red_bull": .375,
					"mclaren": 0,
					"rb": 1.363,
					"alpine": 1.991,
					"audi": 1.439,
					"williams": 2.427,
					"haas": 2.261,
					"aston_martin": 4.693,
					"cadillac": 3.532
				},
				"straight": {
					"aston_martin": 6.329,
					"cadillac": 4.43,
					"alpine": 3.481,
					"red_bull": 5.696,
					"mercedes": 2.215,
					"haas": 5.063,
					"rb": 0,
					"williams": 4.43,
					"ferrari": 3.165,
					"audi": 2.215,
					"mclaren": 2.215
				},
				"slowCorners": {
					"aston_martin": 5.994,
					"cadillac": 3.113,
					"alpine": 2.497,
					"red_bull": .371,
					"mercedes": 1.084,
					"haas": 2.169,
					"rb": .317,
					"williams": 3.295,
					"ferrari": 0,
					"audi": 1.724,
					"mclaren": 1.388
				},
				"highCorners": {
					"aston_martin": 5.982,
					"cadillac": 3.89,
					"alpine": 2.713,
					"red_bull": .292,
					"mercedes": 0,
					"haas": 2.563,
					"rb": .446,
					"williams": 2.702,
					"ferrari": .298,
					"audi": .67,
					"mclaren": .23
				},
				"aero": {
					"aston_martin": 5.933,
					"cadillac": 3.937,
					"alpine": 2.874,
					"red_bull": 2.771,
					"mercedes": .885,
					"haas": 3.59,
					"rb": 0,
					"williams": 3.343,
					"ferrari": 1.508,
					"audi": 1.219,
					"mclaren": 1
				}
			},
			"corners": {
				"slow": 3,
				"medium": 3,
				"high": 3
			},
			"sessions": {
				"qualifying": 11330,
				"race": 11334
			}
		},
		"11": {
			"raceName": "Hungarian Grand Prix",
			"gaps": {
				"quali": {
					"cadillac": 4.765,
					"williams": 4.422,
					"aston_martin": 3.369,
					"ferrari": .016,
					"mercedes": .352,
					"red_bull": .671,
					"mclaren": 0,
					"alpine": 2.12,
					"audi": 1.855,
					"haas": 3.273,
					"rb": 1.391
				},
				"race": {
					"mclaren": 0,
					"red_bull": .762,
					"ferrari": .456,
					"mercedes": .746,
					"rb": 2.287,
					"audi": 2.265,
					"alpine": 2.599,
					"haas": 3.393,
					"aston_martin": 2.869,
					"williams": 3.724,
					"cadillac": 4.401
				},
				"straight": {
					"cadillac": 2.367,
					"williams": 0,
					"aston_martin": 3.55,
					"ferrari": 1.775,
					"mercedes": 1.183,
					"red_bull": 2.663,
					"mclaren": 2.367,
					"alpine": .888,
					"audi": 1.775,
					"haas": 1.183,
					"rb": 2.663
				},
				"slowCorners": {
					"cadillac": 7.894,
					"williams": 6.17,
					"aston_martin": 3.94,
					"ferrari": 0,
					"mercedes": 1.824,
					"red_bull": 2.984,
					"mclaren": 1.945,
					"alpine": 3.281,
					"audi": 4.04,
					"haas": 5.099,
					"rb": 2.594
				},
				"highCorners": {
					"cadillac": 8.18,
					"williams": 7.634,
					"aston_martin": 4.776,
					"ferrari": 1.313,
					"mercedes": 1.106,
					"red_bull": 0,
					"mclaren": .633,
					"alpine": 4.912,
					"audi": 3.141,
					"haas": 5.501,
					"rb": 3.731
				},
				"aero": {
					"cadillac": 4.129,
					"williams": 2.673,
					"aston_martin": 3.019,
					"ferrari": .399,
					"mercedes": 0,
					"red_bull": .187,
					"mclaren": .355,
					"alpine": 1.756,
					"audi": 1.314,
					"haas": 2.198,
					"rb": 2.053
				}
			},
			"corners": {
				"slow": 5,
				"medium": 3,
				"high": 1
			},
			"sessions": {
				"qualifying": 11338,
				"race": 11342
			}
		},
		"12": {
			"raceName": "Dutch Grand Prix",
			"gaps": {
				"quali": {
					"audi": 1.287,
					"haas": 2.774,
					"aston_martin": 3.495,
					"rb": 1.436,
					"cadillac": 4.508,
					"williams": 2.837,
					"ferrari": .465,
					"red_bull": .639,
					"alpine": 2.042,
					"mclaren": 0,
					"mercedes": .143
				},
				"race": {
					"alpine": 2.749,
					"audi": 2.362,
					"rb": 2.754,
					"williams": 3.762,
					"haas": 3.608,
					"aston_martin": 3.422,
					"cadillac": 4.397,
					"mercedes": .316,
					"mclaren": .255,
					"ferrari": 0,
					"red_bull": 1.732
				},
				"straight": {
					"audi": 4.688,
					"haas": 4.063,
					"aston_martin": 5,
					"rb": 1.563,
					"cadillac": 5.312,
					"williams": 1.25,
					"ferrari": 1.563,
					"red_bull": 2.5,
					"alpine": 0,
					"mclaren": 2.187,
					"mercedes": .938
				},
				"slowCorners": {
					"audi": 2.801,
					"haas": 5.195,
					"aston_martin": 4.779,
					"rb": 3.102,
					"cadillac": 5.717,
					"williams": 4.368,
					"ferrari": 0,
					"red_bull": 2.239,
					"alpine": 3.258,
					"mclaren": 1.423,
					"mercedes": 1.708
				},
				"highCorners": {
					"audi": 3.667,
					"haas": 4.034,
					"aston_martin": 5.318,
					"rb": 4.53,
					"cadillac": 9.156,
					"williams": 5.637,
					"ferrari": .976,
					"red_bull": 2.7,
					"alpine": 5.584,
					"mclaren": 0,
					"mercedes": 2.16
				},
				"aero": {
					"audi": 3.084,
					"haas": 2.954,
					"aston_martin": 4.065,
					"rb": 1.953,
					"cadillac": 6.141,
					"williams": 2.35,
					"ferrari": .176,
					"red_bull": 1.506,
					"alpine": 1.698,
					"mclaren": 0,
					"mercedes": .455
				}
			},
			"corners": {
				"slow": 4,
				"medium": 2,
				"high": 3
			},
			"sessions": {
				"qualifying": 11349,
				"race": 11353
			}
		},
		"13": {
			"raceName": "Italian Grand Prix",
			"gaps": {
				"quali": {
					"red_bull": .347,
					"aston_martin": 4.113,
					"haas": 1.186,
					"williams": 2.038,
					"cadillac": 3.152,
					"ferrari": .267,
					"audi": .894,
					"mclaren": .22,
					"mercedes": .073,
					"rb": .611,
					"alpine": 0
				},
				"race": {
					"mercedes": 0,
					"mclaren": 1.161,
					"ferrari": 1.716,
					"alpine": 1.527,
					"red_bull": .849,
					"rb": 2.257,
					"audi": 1.639,
					"haas": 2.792,
					"williams": 1.91,
					"cadillac": 3.763
				},
				"straight": {
					"red_bull": 2.719,
					"aston_martin": 7.251,
					"haas": 1.511,
					"williams": .906,
					"cadillac": 4.532,
					"ferrari": 1.208,
					"audi": 2.719,
					"mclaren": .906,
					"mercedes": 2.115,
					"rb": 3.625,
					"alpine": 0
				},
				"slowCorners": {
					"red_bull": 1.5,
					"aston_martin": 2.79,
					"haas": 1.144,
					"williams": 0,
					"cadillac": 4.135,
					"ferrari": 2.127,
					"audi": 3.283,
					"mclaren": 1.368,
					"mercedes": 1.047,
					"rb": .43,
					"alpine": 6.074
				},
				"highCorners": {
					"red_bull": 1.987,
					"aston_martin": 4.736,
					"haas": 2.238,
					"williams": 5.228,
					"cadillac": 7.027,
					"ferrari": 0,
					"audi": 1.877,
					"mclaren": 1.428,
					"mercedes": 2.817,
					"rb": 1.83,
					"alpine": .4
				},
				"aero": {
					"red_bull": 2.153,
					"aston_martin": 5.793,
					"haas": 1.674,
					"williams": 2.867,
					"cadillac": 5.579,
					"ferrari": .404,
					"audi": 2.098,
					"mclaren": .967,
					"mercedes": 2.266,
					"rb": 2.528,
					"alpine": 0
				}
			},
			"corners": {
				"slow": 2,
				"medium": 1,
				"high": 3
			},
			"sessions": {
				"qualifying": 11357,
				"race": 11361
			}
		},
		"14": {
			"raceName": "Spanish Grand Prix",
			"gaps": {
				"quali": {
					"cadillac": 4.453,
					"mercedes": .012,
					"red_bull": .152,
					"aston_martin": 3.881,
					"williams": 3.793,
					"rb": 1.325,
					"ferrari": .206,
					"audi": 1.524,
					"mclaren": 0,
					"haas": 2.007,
					"alpine": 1.175
				},
				"race": {
					"mclaren": 0,
					"red_bull": .56,
					"mercedes": .131,
					"ferrari": .584,
					"alpine": 1.753,
					"rb": 2.188,
					"haas": 2.27,
					"audi": 2.019,
					"williams": 3.79,
					"cadillac": 4.566,
					"aston_martin": 3.644
				},
				"straight": {
					"cadillac": 7.492,
					"mercedes": 0,
					"red_bull": 2.28,
					"aston_martin": 3.583,
					"williams": 4.56,
					"rb": 1.954,
					"ferrari": 2.28,
					"audi": 1.629,
					"mclaren": .977,
					"haas": 1.954,
					"alpine": 1.303
				},
				"slowCorners": {
					"cadillac": 3.934,
					"mercedes": 0,
					"red_bull": .84,
					"aston_martin": 4.58,
					"williams": 4.213,
					"rb": 2.078,
					"ferrari": 1.056,
					"audi": .842,
					"mclaren": 1.636,
					"haas": 2.784,
					"alpine": 1.912
				},
				"highCorners": {
					"cadillac": 6.731,
					"mercedes": 1.7,
					"red_bull": 1.924,
					"aston_martin": 5.52,
					"williams": 7.086,
					"rb": 4.351,
					"ferrari": 0,
					"audi": 4.389,
					"mclaren": .912,
					"haas": 5.507,
					"alpine": 3.726
				},
				"aero": {
					"cadillac": 6.261,
					"mercedes": 0,
					"red_bull": 1.252,
					"aston_martin": 3.701,
					"williams": 4.973,
					"rb": 2.303,
					"ferrari": .29,
					"audi": 2.159,
					"mclaren": .094,
					"haas": 2.881,
					"alpine": 1.664
				}
			},
			"corners": {
				"slow": 6,
				"medium": 1,
				"high": 1
			},
			"sessions": {
				"qualifying": 11365,
				"race": 11369
			}
		}
	}
} };
//#endregion
//#region scripts/pace/metrics.ts
function median(values) {
	const sorted = [...values].sort((a, b) => a - b);
	const mid = Math.floor(sorted.length / 2);
	return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}
function percentile(values, p) {
	const sorted = [...values].sort((a, b) => a - b);
	return sorted[Math.min(sorted.length - 1, Math.floor(p * sorted.length))];
}
function groupBy(items, key) {
	const groups = /* @__PURE__ */ new Map();
	for (const item of items) {
		const k = key(item);
		if (k === void 0) continue;
		groups.set(k, [...groups.get(k) ?? [], item]);
	}
	return groups;
}
function timeGaps(values) {
	const best = Math.min(...values.values());
	return Object.fromEntries([...values].map(([team, v]) => [team, (v / best - 1) * 100]));
}
function speedGaps(values) {
	const best = Math.max(...values.values());
	return Object.fromEntries([...values].map(([team, v]) => [team, (1 - v / best) * 100]));
}
const round3 = (n) => Math.round(n * 1e3) / 1e3;
function roundGaps(gaps) {
	return Object.fromEntries(Object.entries(gaps).map(([team, gap]) => [team, round3(gap)]));
}
function qualifyingGaps(laps, teamOf) {
	const best = /* @__PURE__ */ new Map();
	for (const lap of laps) {
		const team = teamOf(lap.driver_number);
		if (!team || !lap.lap_duration || lap.is_pit_out_lap) continue;
		best.set(team, Math.min(best.get(team) ?? Infinity, lap.lap_duration));
	}
	return best.size ? timeGaps(best) : {};
}
function fastestLapPerTeam(laps, teamOf) {
	const best = /* @__PURE__ */ new Map();
	for (const lap of laps) {
		const team = teamOf(lap.driver_number);
		if (!team || !lap.lap_duration || !lap.date_start || lap.is_pit_out_lap) continue;
		const current = best.get(team);
		if (!current || lap.lap_duration < current.lap_duration) best.set(team, lap);
	}
	return best;
}
function neutralisedLaps(messages) {
	const laps = /* @__PURE__ */ new Set();
	let start = null;
	for (const m of [...messages].sort((a, b) => a.date.localeCompare(b.date))) {
		const lap = m.lap_number;
		if (lap === null) continue;
		const deployed = m.category === "SafetyCar" && m.message.includes("DEPLOYED");
		const red = m.category === "Flag" && m.flag === "RED";
		const ended = m.category === "SafetyCar" && (m.message.includes("ENDING") || m.message.includes("IN THIS LAP"));
		const resumed = m.category === "Flag" && m.flag === "GREEN" && start !== null;
		if ((deployed || red) && start === null) start = lap;
		if ((ended || resumed) && start !== null) {
			for (let l = start - 1; l <= lap + 1; l++) laps.add(l);
			start = null;
		}
	}
	if (start !== null) for (let l = start - 1; l <= start + 3; l++) laps.add(l);
	return laps;
}
function raceGaps(laps, stints, messages, teamOf) {
	const neutralised = neutralisedLaps(messages);
	const inLaps = /* @__PURE__ */ new Set();
	const lastStint = /* @__PURE__ */ new Map();
	for (const s of stints) lastStint.set(s.driver_number, Math.max(lastStint.get(s.driver_number) ?? 0, s.stint_number));
	for (const s of stints) if (s.stint_number < (lastStint.get(s.driver_number) ?? 0)) inLaps.add(`${s.driver_number}:${s.lap_end}`);
	const clean = laps.filter((l) => l.lap_duration !== null && l.lap_number > 1 && !l.is_pit_out_lap && !neutralised.has(l.lap_number) && !inLaps.has(`${l.driver_number}:${l.lap_number}`));
	const ratiosByTeam = /* @__PURE__ */ new Map();
	for (const [, lapGroup] of groupBy(clean, (l) => String(l.lap_number))) {
		const lapMedian = median(lapGroup.map((l) => l.lap_duration));
		const teamBest = /* @__PURE__ */ new Map();
		for (const l of lapGroup) {
			const team = teamOf(l.driver_number);
			if (!team || l.lap_duration > lapMedian * 1.05) continue;
			teamBest.set(team, Math.min(teamBest.get(team) ?? Infinity, l.lap_duration));
		}
		if (teamBest.size < 6) continue;
		const fastest = Math.min(...teamBest.values());
		for (const [team, time] of teamBest) ratiosByTeam.set(team, [...ratiosByTeam.get(team) ?? [], time / fastest]);
	}
	const medians = new Map([...ratiosByTeam].filter(([, r]) => r.length >= 5).map(([team, r]) => [team, median(r)]));
	return medians.size ? timeGaps(medians) : {};
}
function straightLineGaps(lapsBySession, teamOf) {
	const speeds = /* @__PURE__ */ new Map();
	for (const laps of lapsBySession) for (const l of laps) {
		const team = teamOf(l.driver_number);
		if (!team || !l.st_speed || l.is_pit_out_lap) continue;
		speeds.set(team, [...speeds.get(team) ?? [], l.st_speed]);
	}
	const p90 = new Map([...speeds].filter(([, s]) => s.length >= 5).map(([team, s]) => [team, percentile(s, .9)]));
	return p90.size ? speedGaps(p90) : {};
}
const SLOW_KMH = 130;
const HIGH_KMH = 185;
const PROMINENCE_KMH = 15;
const MIN_REGAIN_KMH = 5;
const POINTS = 1e3;
const ZONE = 15;
const NEIGHBOURHOOD = 50;
const MAX_SHIFT = 30;
const OUTLIER = .1;
function toTrace(samples) {
	if (samples.length < 50) return void 0;
	const sorted = [...samples].sort((a, b) => a.date.localeCompare(b.date));
	const distance = [0];
	for (let i = 1; i < sorted.length; i++) {
		const dt = (Date.parse(sorted[i].date) - Date.parse(sorted[i - 1].date)) / 1e3;
		distance.push(distance[i - 1] + sorted[i - 1].speed / 3.6 * dt);
	}
	const total = distance[distance.length - 1];
	const trace = [];
	let j = 0;
	for (let k = 0; k < POINTS; k++) {
		const d = k / POINTS * total;
		while (j < distance.length - 2 && distance[j + 1] < d) j++;
		const span = distance[j + 1] - distance[j] || 1;
		const t = Math.min(1, Math.max(0, (d - distance[j]) / span));
		trace.push(sorted[j].speed + t * (sorted[j + 1].speed - sorted[j].speed));
	}
	return trace;
}
const at = (trace, k) => trace[(k % POINTS + POINTS) % POINTS];
function align(reference, trace) {
	let bestShift = 0;
	let bestError = Infinity;
	for (let shift = -MAX_SHIFT; shift <= MAX_SHIFT; shift++) {
		let error = 0;
		for (let k = 0; k < POINTS; k++) error += (reference[k] - at(trace, k + shift)) ** 2;
		if (error < bestError) {
			bestError = error;
			bestShift = shift;
		}
	}
	return reference.map((_, k) => at(trace, k + bestShift));
}
function findApexes(trace) {
	const apexes = [];
	for (let k = 1; k < POINTS - 1; k++) {
		if (trace[k] > trace[k - 1] || trace[k] > trace[k + 1]) continue;
		let before = 0;
		let after = 0;
		for (let d = 1; d <= NEIGHBOURHOOD; d++) {
			before = Math.max(before, at(trace, k - d));
			after = Math.max(after, at(trace, k + d));
		}
		const drop = before - trace[k];
		const regain = after - trace[k];
		if (Math.max(drop, regain) < PROMINENCE_KMH || Math.min(drop, regain) < MIN_REGAIN_KMH) continue;
		const last = apexes[apexes.length - 1];
		if (last !== void 0 && k - last < ZONE * 2) {
			if (trace[k] < trace[last]) apexes[apexes.length - 1] = k;
			continue;
		}
		apexes.push(k);
	}
	return apexes;
}
function cornerSpeed(trace, apex) {
	let sum = 0;
	for (let d = -ZONE; d <= ZONE; d++) sum += at(trace, apex + d);
	return sum / (ZONE * 2 + 1);
}
function cornerGaps(traces, referenceTeam) {
	const empty = {
		slow: {},
		high: {},
		corners: {
			slow: 0,
			medium: 0,
			high: 0
		}
	};
	const reference = traces.get(referenceTeam);
	if (!reference) return empty;
	const aligned = new Map([...traces].map(([team, trace]) => [team, team === referenceTeam ? trace : align(reference, trace)]));
	const ratios = {
		slow: /* @__PURE__ */ new Map(),
		high: /* @__PURE__ */ new Map()
	};
	const corners = {
		slow: 0,
		medium: 0,
		high: 0
	};
	for (const apex of findApexes(reference)) {
		const speeds = new Map([...aligned].map(([team, trace]) => [team, cornerSpeed(trace, apex)]));
		const fieldMedian = median([...speeds.values()]);
		for (const [team, v] of speeds) if (Math.abs(v / fieldMedian - 1) > OUTLIER) speeds.delete(team);
		if (speeds.size < 6) continue;
		const kind = reference[apex] < SLOW_KMH ? "slow" : reference[apex] >= HIGH_KMH ? "high" : "medium";
		corners[kind]++;
		if (kind === "medium") continue;
		const best = Math.max(...speeds.values());
		for (const [team, v] of speeds) ratios[kind].set(team, [...ratios[kind].get(team) ?? [], v / best]);
	}
	const toGaps = (byTeam) => {
		if (!byTeam.size) return {};
		return speedGaps(new Map([...byTeam].map(([team, r]) => [team, r.reduce((a, b) => a + b, 0) / r.length])));
	};
	return {
		slow: toGaps(ratios.slow),
		high: toGaps(ratios.high),
		corners
	};
}
function aeroGaps(straight, high) {
	const teams = Object.keys(straight).filter((team) => team in high);
	if (!teams.length) return {};
	const combined = new Map(teams.map((team) => [team, (straight[team] + high[team]) / 2]));
	const best = Math.min(...combined.values());
	return Object.fromEntries([...combined].map(([team, gap]) => [team, gap - best]));
}
//#endregion
//#region scripts/pace/compute.ts
async function fetchRaceTeams(deps, season) {
	const byRound = /* @__PURE__ */ new Map();
	let offset = 0;
	let total;
	do {
		const page = await deps.jolpica(`/${season}/results.json?limit=100&offset=${offset}`);
		total = parseInt(page.MRData.total);
		for (const race of page.MRData.RaceTable.Races) {
			const round = parseInt(race.round);
			const entry = byRound.get(round) ?? {
				round,
				raceName: race.raceName,
				date: race.date,
				teams: /* @__PURE__ */ new Map()
			};
			for (const r of race.Results ?? []) entry.teams.set(parseInt(r.number), r.Constructor.constructorId);
			byRound.set(round, entry);
		}
		offset += 100;
	} while (offset < total);
	return byRound;
}
async function fetchSessionIndex(deps, season) {
	const [meetings, sessions] = await Promise.all([deps.openF1(`/meetings?year=${season}`), deps.openF1(`/sessions?year=${season}`)]);
	return {
		meetings,
		sessions
	};
}
function findSessions(index, race) {
	const meeting = index.meetings.find((m) => !m.is_cancelled && m.date_start.slice(0, 10) <= race.date && race.date <= m.date_end.slice(0, 10));
	const inMeeting = (name) => index.sessions.find((s) => s.meeting_key === meeting?.meeting_key && s.session_name === name);
	const qualifying = inMeeting("Qualifying");
	const raceSession = inMeeting("Race");
	return qualifying && raceSession ? {
		qualifying: qualifying.session_key,
		race: raceSession.session_key
	} : void 0;
}
const openF1Time = (ms) => new Date(ms).toISOString().replace("Z", "");
async function computeRound(deps, race, sessions) {
	const teamOf = (n) => race.teams.get(n);
	const qualiLaps = await deps.openF1(`/laps?session_key=${sessions.qualifying}`);
	const raceLaps = await deps.openF1(`/laps?session_key=${sessions.race}`);
	const messages = await deps.openF1(`/race_control?session_key=${sessions.race}`);
	const stints = await deps.openF1(`/stints?session_key=${sessions.race}`);
	const quali = qualifyingGaps(qualiLaps, teamOf);
	const straight = straightLineGaps([qualiLaps, raceLaps], teamOf);
	const traces = /* @__PURE__ */ new Map();
	for (const [team, lap] of fastestLapPerTeam(qualiLaps, teamOf)) {
		const start = Date.parse(lap.date_start);
		const end = start + lap.lap_duration * 1e3;
		const trace = toTrace(await deps.openF1(`/car_data?session_key=${sessions.qualifying}&driver_number=${lap.driver_number}&date>=${openF1Time(start)}&date<=${openF1Time(end)}`));
		if (trace) traces.set(team, trace);
	}
	const referenceTeam = Object.entries(quali).sort((a, b) => a[1] - b[1])[0]?.[0];
	const corners = cornerGaps(traces, referenceTeam ?? "");
	return {
		raceName: race.raceName,
		gaps: {
			quali: roundGaps(quali),
			race: roundGaps(raceGaps(raceLaps, stints, messages, teamOf)),
			straight: roundGaps(straight),
			slowCorners: roundGaps(corners.slow),
			highCorners: roundGaps(corners.high),
			aero: roundGaps(aeroGaps(straight, corners.high))
		},
		corners: corners.corners,
		sessions
	};
}
//#endregion
//#region server/pace.ts
const seed = paceRatings_default;
const DAY = 1440 * 60 * 1e3;
const LOCK_MS = 600 * 1e3;
const MAX_ATTEMPTS = 3;
const RETRY_AFTER_MS = 360 * 60 * 1e3;
const blobPath = (season) => `pace/${season}.json`;
async function readStored(season) {
	const blob = await get(blobPath(season), { access: "private" });
	if (!blob || blob.statusCode !== 200) return {
		rounds: {},
		attempts: {}
	};
	return await new Response(blob.stream).json();
}
async function writeStored(season, stored) {
	await put(blobPath(season), JSON.stringify(stored), {
		access: "private",
		addRandomSuffix: false,
		allowOverwrite: true,
		contentType: "application/json"
	});
}
const deps = {
	openF1: (path) => fetchJson(openF1Url(path), true),
	jolpica: (path) => fetchJson(jolpicaUrl(path), false)
};
async function generate(season, round) {
	const finish = async (update) => {
		const latest = await readStored(season);
		update(latest);
		delete latest.lock;
		await writeStored(season, latest);
	};
	try {
		const [results, index] = await Promise.all([fetchRaceTeams(deps, season), fetchSessionIndex(deps, season)]);
		const race = results.get(round);
		const sessions = race && findSessions(index, race);
		if (!race || !sessions) throw new Error("no results or OpenF1 sessions yet");
		const pace = await computeRound(deps, race, sessions);
		await finish((s) => {
			s.rounds[round] = pace;
			delete s.attempts[round];
		});
		console.log(`R${round}: pace computed for ${Object.keys(pace.gaps.quali).length} teams`);
	} catch (err) {
		const reason = err.message;
		await finish((s) => {
			const previous = s.attempts[round];
			s.attempts[round] = {
				count: (previous?.count ?? 0) + 1,
				last: new Date(Date.now()).toISOString(),
				reason
			};
		});
		console.warn(`R${round}: ${reason}`);
	}
}
async function dueRound(season, stored, now) {
	const known = new Set([...Object.keys(seed[season]?.rounds ?? {}), ...Object.keys(stored.rounds)].map(Number));
	return [...(await fetchRaceTeams(deps, season)).values()].filter((r) => r.teams.size > 0 && !known.has(r.round)).filter((r) => now >= Date.parse(`${r.date}T00:00:00Z`) + 1 * DAY).filter((r) => {
		const attempt = stored.attempts[r.round];
		return !attempt || attempt.count < MAX_ATTEMPTS && now - Date.parse(attempt.last) > RETRY_AFTER_MS;
	}).sort((a, b) => a.round - b.round)[0]?.round;
}
async function GET(request) {
	const url = new URL(request.url);
	const currentYear = (/* @__PURE__ */ new Date()).getFullYear();
	const season = Number(url.searchParams.get("season") ?? currentYear);
	if (!Number.isInteger(season) || season < 2023 || season > currentYear) return Response.json({ error: "season must be between 2023 and the current year" }, { status: 400 });
	const stored = await readStored(season);
	const now = Date.now();
	let computing = null;
	if (stored.lock && now - Date.parse(stored.lock.startedAt) < LOCK_MS) computing = stored.lock.round;
	else {
		const round = await dueRound(season, stored, now);
		if (round !== void 0) {
			stored.lock = {
				round,
				startedAt: new Date(now).toISOString()
			};
			await writeStored(season, stored);
			computing = round;
			waitUntil(generate(season, round));
		}
	}
	return Response.json({
		season,
		rounds: {
			...seed[season]?.rounds,
			...stored.rounds
		},
		computing
	}, { headers: { "Cache-Control": "no-store" } });
}
//#endregion
export { GET };
